### ISSUE TITLE
snap pw checker?

### ISSUE THREAD

**Issue by hejhopsa** [Fah4d/Remax-CheckSnap#2]
hello Fah4d, 

is it possible for you to make also pw checker (paid)?

**Comment by Fah4d** [comment]
sorry i can't , cuz snapchat login has captcha .

**Comment by hejhopsa** [comment]
Hi Fah4d,

Thank you for reaching out.
There are a lot services that solve captcha automatically: Death By
Captcha, anti-captcha(.)com , imagetyperz , 2captcha , bestcaptchasolve
https://github.com/imagetyperz-api/imagetyperz-api-python3
https://github.com/ozgurkayaist/Google-Recaptcha-Solver-SeleniumAutomation
https://github.com/deathbycaptcha/python_client_library
https://github.com/bestcaptchasolver/bestcaptchasolver-ruby

what do you think? :-)

śr., 21 kwi 2021 o 00:59 Remax Alghamdi ***@***.***>
napisał(a):

**Comment by Fah4d** [comment]
snapchat has another captcha , but selenium solve the problem .
anyway i don't use selenium .
thanks for your help .
